/*
Package gocode provides the Go code-generation backend and Go AST builders.

[Context]
Build language-neutral nodes with the root codegen package (File, Expr, Stmt, engine). Build Go-specific declarations and types with this package, then render with GoFileRender.
*/
package gocode

import (
	"fmt"
	"time"

	"codegen"
	"codegen/internal/ast"
	"codegen/internal/emit"
	"codegen/internal/engine"
	"codegen/internal/goast"
	"codegen/internal/goengine"
)

/*
GoEngineCreate returns an engine with all default Go node renderers registered.

[Returns]
Configured engine for EngineRender.
*/
func GoEngineCreate() *engine.Engine {
	return goengine.GoEngineCreate()
}

/*
GoEmitterCreate returns an emitter with Go-default tab indentation per level.

[Returns]
Fresh emitter for a single render pass.
*/
func GoEmitterCreate() emit.Emitter {
	return goengine.GoEmitterCreate()
}

/*
GoFileRender renders a file AST to Go source text.

[Parameters]
file — root file node with elements.

[Returns]
Generated source or a render error.

[Side Effects]
None; uses a fresh emitter internally.
*/
func GoFileRender(file goast.File) (string, error) {
	return GoFileRenderWithOptions(file, goast.RenderOptionsDefault())
}

/*
GoFileRenderWithOptions renders a file AST to Go source text using the given render options.

[Parameters]
file — root file node with elements.
options — Go backend render configuration attached to the render context.

[Returns]
Generated source or a render error.
*/
func GoFileRenderWithOptions(file goast.File, options goast.RenderOptions) (string, error) {
	eng := GoEngineCreate()
	emitter := GoEmitterCreate()
	ctx := &engine.RenderContext{
		Engine:  eng,
		Emitter: &emitter,
		Data:    options,
	}
	if err := engine.EngineRenderNode(ctx, file); err != nil {
		return "", err
	}
	return emit.EmitterRender(&emitter), nil
}

/*
GoBlankLine returns a file element that inserts vertical spacing.

[Returns]
FileElement wrapping BlankLine.
*/
func GoBlankLine() codegen.FileElement {
	return codegen.FileElementFrom(goast.LayoutBlankLineNew())
}

/*
GoLineComment returns a file element for a single-line comment.

[Parameters]
text — comment body without leading slashes.

[Returns]
FileElement wrapping LineComment.
*/
func GoLineComment(text string) codegen.FileElement {
	return codegen.FileElementFrom(goast.LayoutLineCommentNew(text))
}

/*
GoBuildConstraint returns a file element for a //go:build directive.

[Parameters]
tag — build constraint expression (for example "linux" or "windows").
*/
func GoBuildConstraint(tag string) codegen.FileElement {
	return codegen.FileElementFrom(goast.LayoutBuildConstraintNew(tag))
}

/*
GoBlockComment returns a file element for multiple comment lines.

[Returns]
FileElement wrapping BlockComment.
*/
func GoBlockComment(lines ...string) codegen.FileElement {
	return codegen.FileElementFrom(goast.LayoutBlockCommentNew(lines...))
}

const goGeneratedHeaderTimeFormat = "2006-01-02 15:04:05 MST"

/*
GoGeneratedFileHeader returns layout elements for an auto-generated file banner.

[Parameters]
toolLabel — generator name shown in the header comment.
generatedAt — timestamp recorded in the header.

[Returns]
Line comment and trailing blank line elements.
*/
func GoGeneratedFileHeader(toolLabel string, generatedAt time.Time) []codegen.FileElement {
	timestamp := generatedAt.Format(goGeneratedHeaderTimeFormat)
	return []codegen.FileElement{
		GoLineComment(fmt.Sprintf("This file was auto-generated by '%s' at %s", toolLabel, timestamp)),
		GoBlankLine(),
	}
}

/*
GoStringLit constructs a string literal expression for Go output.

[Parameters]
value — string value.

[Returns]
A StringLitExpr node.
*/
func GoStringLit(value string) ast.Expr {
	return goast.ExprStringLit(value)
}

/*
GoIdent constructs an identifier expression for Go output.

[Parameters]
name — identifier spelling.

[Returns]
An IdentExpr node.
*/
func GoIdent(name string) ast.Expr {
	return goast.ExprIdent(name)
}

/*
GoSelector constructs a selector expression for Go output.

[Parameters]
base — left-hand expression.
name — selected identifier.

[Returns]
A SelectorExpr node.
*/
func GoSelector(base ast.Expr, name string) ast.Expr {
	return goast.ExprSelector(base, name)
}

/*
GoCall constructs a call expression for Go output.

[Parameters]
callee — called expression.
args — argument expressions.

[Returns]
A CallExpr node.
*/
func GoCall(callee ast.Expr, args ...ast.Expr) ast.Expr {
	return goast.ExprCall(callee, args...)
}

/*
GoSyscoreCString builds a call to syscore.SYSCORE_C_StringToCStringFirstByte for a Vulkan symbol name.

[Parameters]
symbol — C function name such as vkDestroyInstance.

[Returns]
Call expression AST node.
*/
func GoSyscoreCString(symbol string) ast.Expr {
	return GoCall(
		GoSelector(GoIdent("syscore"), "SYSCORE_C_StringToCStringFirstByte"),
		GoStringLit(symbol),
	)
}

/*
GoSyscoreBindAddress builds a call to syscore.SYSCORE_Pure_FunctionBindAddress.

[Returns]
Call expression AST node.
*/
func GoSyscoreBindAddress(target ast.Expr, address ast.Expr) ast.Expr {
	return GoCall(
		GoSelector(GoIdent("syscore"), "SYSCORE_Pure_FunctionBindAddress"),
		target,
		address,
	)
}

/*
GoFmtErrorf builds a call to fmt.Errorf.

[Returns]
Call expression AST node.
*/
func GoFmtErrorf(format string, args ...ast.Expr) ast.Expr {
	allArgs := make([]ast.Expr, 0, len(args)+1)
	allArgs = append(allArgs, GoStringLit(format))
	allArgs = append(allArgs, args...)
	return GoCall(GoSelector(GoIdent("fmt"), "Errorf"), allArgs...)
}

/*
GoPanicFmt builds panic(fmt.Errorf(...)).

[Returns]
Expression suitable for ExprStmt.
*/
func GoPanicFmt(format string, args ...ast.Expr) ast.Expr {
	return GoCall(GoIdent("panic"), GoFmtErrorf(format, args...))
}
